# Data audit

This notebook helps checks the raw files before I build the cleaned datasets; it is supported by manually looking at the files.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

pd.set_option("display.max_columns", 20)
pd.set_option("display.max_colwidth", 120)

base_path = Path("/Users/eduvieojoboh/Downloads/Visual_analytics")
raw_path = base_path / "Data" / "raw"
lookup_path = raw_path / "lookups"
output_path = base_path / "Data" / "outputs"

output_path.mkdir(parents=True, exist_ok=True)

In [2]:
files = {
    "2011_age_la": raw_path / "2011" / "2011_age_LA.csv",
    "2011_sex_la": raw_path / "2011" / "2011_sex_LA.csv",
    "2011_ethnicity_la": raw_path / "2011" / "2011_ethnicity_LA.csv",
    "2011_unpaid_care_la": raw_path / "2011" / "2011_unpaid_care_LA.csv",
    "2011_economic_activity_la": raw_path / "2011" / "2011_economic_activity_LA.csv",

    "2021_age_la": raw_path / "2021" / "2021_age_LA.csv",
    "2021_sex_la": raw_path / "2021" / "2021_sex_LA.csv",
    "2021_ethnicity_la": raw_path / "2021" / "2021_ethnicity_LA.csv",
    "2021_unpaid_care_la": raw_path / "2021" / "2021_unpaid_care_LA.csv",
    "2021_economic_activity_la": raw_path / "2021" / "2021_economic_activity_LA.csv",

    "2021_age_msoa": raw_path / "2021" / "2021_age_MSOA.csv",
    "2021_sex_msoa": raw_path / "2021" / "2021_sex_MSOA.csv",
    "2021_ethnicity_msoa": raw_path / "2021" / "2021_ethnicity_MSOA.csv",
    "2021_unpaid_care_msoa": raw_path / "2021" / "2021_unpaid_care_MSOA.csv",
    "2021_economic_activity_msoa": raw_path / "2021" / "2021_economic_activity_MSOA.csv",
}

lookup_files = {
    "msoa_to_la": lookup_path / "MSOA_to_LA.csv",
    "la_2011_to_2021": lookup_path / "2011_to_2021_LA.csv",
}

for name, file in {**files, **lookup_files}.items():
    print(name, "-", file.exists(), "-", file.name)

2011_age_la - True - 2011_age_LA.csv
2011_sex_la - True - 2011_sex_LA.csv
2011_ethnicity_la - True - 2011_ethnicity_LA.csv
2011_unpaid_care_la - True - 2011_unpaid_care_LA.csv
2011_economic_activity_la - True - 2011_economic_activity_LA.csv
2021_age_la - True - 2021_age_LA.csv
2021_sex_la - True - 2021_sex_LA.csv
2021_ethnicity_la - True - 2021_ethnicity_LA.csv
2021_unpaid_care_la - True - 2021_unpaid_care_LA.csv
2021_economic_activity_la - True - 2021_economic_activity_LA.csv
2021_age_msoa - True - 2021_age_MSOA.csv
2021_sex_msoa - True - 2021_sex_MSOA.csv
2021_ethnicity_msoa - True - 2021_ethnicity_MSOA.csv
2021_unpaid_care_msoa - True - 2021_unpaid_care_MSOA.csv
2021_economic_activity_msoa - True - 2021_economic_activity_MSOA.csv
msoa_to_la - True - MSOA_to_LA.csv
la_2011_to_2021 - True - 2011_to_2021_LA.csv

In [3]:
age_2011 = pd.read_csv(files["2011_age_la"])
age_2011.head()

,date,geography,geography code,Rural Urban,Age: All categories: Age; measures: Value,Age: Age under 1; measures: Value,Age: Age 1; measures: Value,Age: Age 2; measures: Value,Age: Age 3; measures: Value,Age: Age 4; measures: Value,...,Age: Age 91; measures: Value,Age: Age 92; measures: Value,Age: Age 93; measures: Value,Age: Age 94; measures: Value,Age: Age 95; measures: Value,Age: Age 96; measures: Value,Age: Age 97; measures: Value,Age: Age 98; measures: Value,Age: Age 99; measures: Value,Age: Age 100 and over; measures: Value
0,2011,Darlington,E06000005,Total,105564,1344,1371,1302,1297,1265,...,148,104,91,69,50,34,26,32,22,28
1,2011,County Durham,E06000047,Total,513242,5884,5645,5602,5826,5617,...,709,461,331,262,215,187,144,87,76,80
2,2011,Hartlepool,E06000001,Total,92028,1097,1176,1155,1159,1111,...,127,63,51,34,29,15,16,15,6,14
3,2011,Middlesbrough,E06000002,Total,138412,1979,1965,1797,1863,1827,...,183,103,90,56,40,46,30,19,12,15
4,2011,Northumberland,E06000057,Total,316028,3148,3150,3205,3325,3175,...,517,377,231,242,183,140,72,62,53,81

In [4]:
care_2021_msoa = pd.read_csv(files["2021_unpaid_care_msoa"])
care_2021_msoa.head()

,date,geography,geography code,Provision of unpaid care: Total: All usual residents aged 5 and over,Provision of unpaid care: Provides no unpaid care,Provision of unpaid care: Provides 19 hours or less unpaid care a week,Provision of unpaid care: Provides 9 hours or less unpaid care a week,Provision of unpaid care: Provides 10 to 19 hours unpaid care a week,Provision of unpaid care: Provides 20 to 49 hours unpaid care a week,Provision of unpaid care: Provides 20 to 34 hours unpaid care a week,Provision of unpaid care: Provides 35 to 49 hours unpaid care a week,Provision of unpaid care: Provides 50 or more hours unpaid care a week
0,2021,City of London 001,E02000001,8372,7876,336,263,73,81,42,39,79
1,2021,Barking and Dagenham 001,E02000002,7628,7072,198,126,72,168,67,101,190
2,2021,Barking and Dagenham 002,E02000003,10588,9855,327,220,107,178,94,84,228
3,2021,Barking and Dagenham 003,E02000004,6245,5719,260,163,97,99,50,49,167
4,2021,Barking and Dagenham 004,E02000005,10108,9419,283,182,101,160,72,88,246

In [5]:
econ_2021_la = pd.read_csv(files["2021_economic_activity_la"])
econ_2021_la.head()

,date,geography,geography code,Economic activity status: Total: All usual residents aged 16 years and over,Economic activity status: Economically active (excluding full-time students),Economic activity status: Economically active (excluding full-time students):In employment,Economic activity status: Economically active (excluding full-time students):In employment:Employee,Economic activity status: Economically active (excluding full-time students): In employment: Employee: Part-time,Economic activity status: Economically active (excluding full-time students): In employment: Employee: Full-time,Economic activity status: Economically active (excluding full-time students):In employment:Self-employed with employees,...,Economic activity status: Economically active and a full-time student:In employment:Self-employed without employees,Economic activity status: Economically active and a full-time student: In employment: Self-employed without employees: Part-time,Economic activity status: Economically active and a full-time student: In employment: Self-employed without employees: Full-time,Economic activity status: Economically active and a full-time student: Unemployed,Economic activity status: Economically inactive,Economic activity status: Economically inactive: Retired,Economic activity status: Economically inactive: Student,Economic activity status: Economically inactive: Looking after home or family,Economic activity status: Economically inactive: Long-term sick or disabled,Economic activity status: Economically inactive: Other
0,2021,Hartlepool,E06000001,74685,39487,36846,32298,9575,22723,872,...,24,16,8,361,33934,17910,3463,4303,5432,2826
1,2021,Middlesbrough,E06000002,113939,58233,53849,47228,14198,33030,1245,...,99,85,14,1431,51691,23267,7974,7527,7879,5044
2,2021,Redcar and Cleveland,E06000003,112340,57807,54282,47224,14167,33057,1294,...,56,39,17,479,52716,32033,4444,5597,7268,3374
3,2021,Stockton-on-Tees,E06000004,158008,89315,84174,73699,19945,53754,1994,...,69,51,18,759,65666,37038,6878,7670,8208,5872
4,2021,Darlington,E06000005,88103,50768,48103,42072,10748,31324,1150,...,32,22,10,368,35774,21930,3229,3899,4179,2537

In [7]:
# Look at shapes and first columns
for name, file in files.items():
    df = pd.read_csv(file, nrows=5)
    print("\n" + name)
    print("shape from sample:", df.shape)
    print("first columns:")
    for col in list(df.columns[:8]):
        print(" -", col)

2011_age_la
shape from sample: (5, 106)
first columns:
 - date
 - geography
 - geography code
 - Rural Urban
 - Age: All categories: Age; measures: Value
 - Age: Age under 1; measures: Value
 - Age: Age 1; measures: Value
 - Age: Age 2; measures: Value

2011_sex_la
shape from sample: (5, 7)
first columns:
 - date
 - geography
 - geography code
 - Rural Urban
 - Sex: All persons; measures: Value
 - Sex: Males; measures: Value
 - Sex: Females; measures: Value

2011_ethnicity_la
shape from sample: (5, 28)
first columns:
 - date
 - geography
 - geography code
 - Rural Urban
 - Ethnic Group: All categories: Ethnic group; measures: Value
 - Ethnic Group: White; measures: Value
 - Ethnic Group: White: English/Welsh/Scottish/Northern Irish/British; measures: Value
 - Ethnic Group: White: Irish; measures: Value

2011_unpaid_care_la
shape from sample: (5, 9)
first columns:
 - date
 - geography
 - geography code
 - Rural Urban
 - Care Provision: All categories: Provision of unpaid care; measures: Value
 - Care Provision: Provides no unpaid care; measures: Value
 - Care Provision: Provides 1 to 19 hours unpaid care a week; measures: Value
 - Care Provision: Provides 20 to 49 hours unpaid care a week; measures: Value

2011_economic_activity_la
shape from sample: (5, 201)
first columns:
 - date
 - geography
 - geography code
 - Sex: All persons; Age: All categories: Age 16 and over; Economic Activity: All categories: Economic activity; measures: Value
 - Sex: All persons; Age: All categories: Age 16 and over; Economic Activity: Economically active: Total; measures: Value
 - Sex: All persons; Age: All categories: Age 16 and over; Economic Activity: Economically active: In employment: Total; measures: Value
 - Sex: All persons; Age: All categories: Age 16 and over; Economic Activity: Economically active: In employment: Employee: Total; measures: Value
 - Sex: All persons; Age: All categories: Age 16 and over; Economic Activity: Economically active: In employment: Employee: Part-time (including full-time students); measures: Value

2021_age_la
shape from sample: (5, 116)
first columns:
 - date
 - geography
 - geography code
 - Age: Total; measures: Value
 - Age: Aged 4 years and under; measures: Value
 - Age: Aged under 1 year; measures: Value
 - Age: Aged 1 year; measures: Value
 - Age: Aged 2 years; measures: Value

2021_sex_la
shape from sample: (5, 6)
first columns:
 - date
 - geography
 - geography code
 - Sex: All persons; measures: Value
 - Sex: Female; measures: Value
 - Sex: Male; measures: Value

2021_ethnicity_la
shape from sample: (5, 28)
first columns:
 - date
 - geography
 - geography code
 - Ethnic group: Total: All usual residents
 - Ethnic group: Asian, Asian British or Asian Welsh
 - Ethnic group: Asian, Asian British or Asian Welsh: Bangladeshi
 - Ethnic group: Asian, Asian British or Asian Welsh: Chinese
 - Ethnic group: Asian, Asian British or Asian Welsh: Indian

2021_unpaid_care_la
shape from sample: (5, 12)
first columns:
 - date
 - geography
 - geography code
 - Provision of unpaid care: Total: All usual residents aged 5 and over
 - Provision of unpaid care: Provides no unpaid care
 - Provision of unpaid care: Provides 19 hours or less unpaid care a week
 - Provision of unpaid care: Provides 9 hours or less unpaid care a week
 - Provision of unpaid care: Provides 10 to 19 hours unpaid care a week

2021_economic_activity_la
shape from sample: (5, 34)
first columns:
 - date
 - geography
 - geography code
 - Economic activity status: Total: All usual residents aged 16 years and over
 - Economic activity status: Economically active (excluding full-time students)
 - Economic activity status: Economically active (excluding full-time students):In employment
 - Economic activity status: Economically active (excluding full-time students):In employment:Employee
 - Economic activity status: Economically active (excluding full-time students): In employment: Employee: Part-time

2021_age_msoa
shape from sample: (5, 116)
first columns:
 - date
 - geography
 - geography code
 - Age: Total; measures: Value
 - Age: Aged 4 years and under; measures: Value
 - Age: Aged under 1 year; measures: Value
 - Age: Aged 1 year; measures: Value
 - Age: Aged 2 years; measures: Value

2021_sex_msoa
shape from sample: (5, 6)
first columns:
 - date
 - geography
 - geography code
 - Sex: All persons; measures: Value
 - Sex: Female; measures: Value
 - Sex: Male; measures: Value

2021_ethnicity_msoa
shape from sample: (5, 28)
first columns:
 - date
 - geography
 - geography code
 - Ethnic group: Total: All usual residents
 - Ethnic group: Asian, Asian British or Asian Welsh
 - Ethnic group: Asian, Asian British or Asian Welsh: Bangladeshi
 - Ethnic group: Asian, Asian British or Asian Welsh: Chinese
 - Ethnic group: Asian, Asian British or Asian Welsh: Indian

2021_unpaid_care_msoa
shape from sample: (5, 12)
first columns:
 - date
 - geography
 - geography code
 - Provision of unpaid care: Total: All usual residents aged 5 and over
 - Provision of unpaid care: Provides no unpaid care
 - Provision of unpaid care: Provides 19 hours or less unpaid care a week
 - Provision of unpaid care: Provides 9 hours or less unpaid care a week
 - Provision of unpaid care: Provides 10 to 19 hours unpaid care a week

2021_economic_activity_msoa
shape from sample: (5, 34)
first columns:
 - date
 - geography
 - geography code
 - Economic activity status: Total: All usual residents aged 16 years and over
 - Economic activity status: Economically active (excluding full-time students)
 - Economic activity status: Economically active (excluding full-time students):In employment
 - Economic activity status: Economically active (excluding full-time students):In employment:Employee
 - Economic activity status: Economically active (excluding full-time students): In employment: Employee: Part-time

In [8]:
# Audit checks
def audit_file(name, file):
    df = pd.read_csv(file, low_memory=False)

    if "2011" in name:
        year = "2011"
    else:
        year = "2021"

    if "msoa" in name:
        geography = "MSOA"
    else:
        geography = "LA"

    if "age" in name:
        theme = "age"
    elif "sex" in name:
        theme = "sex"
    elif "ethnicity" in name:
        theme = "ethnicity"
    elif "unpaid_care" in name:
        theme = "unpaid care"
    elif "economic_activity" in name:
        theme = "economic activity"
    else:
        theme = "unknown"

    code_col = "geography code" if "geography code" in df.columns else "not found"
    name_col = "geography" if "geography" in df.columns else "not found"

    if code_col != "not found":
        duplicate_codes = df[code_col].duplicated().sum()
        unique_codes = df[code_col].nunique()
    else:
        duplicate_codes = None
        unique_codes = None

    value_cols = df.select_dtypes(include="number").columns
    negative_values = int((df[value_cols] < 0).sum().sum()) if len(value_cols) > 0 else 0

    return {
        "file": file.name,
        "year": year,
        "geography": geography,
        "theme": theme,
        "rows": len(df),
        "columns": len(df.columns),
        "missing_values": int(df.isna().sum().sum()),
        "duplicate_codes": duplicate_codes,
        "unique_codes": unique_codes,
        "negative_values": negative_values,
        "key_join_column": code_col,
        "area_name_column": name_col,
        "first_few_columns": "; ".join(list(df.columns[:6])),
    }

audit_rows = []

for name, file in files.items():
    audit_rows.append(audit_file(name, file))

audit_table = pd.DataFrame(audit_rows)
display(audit_table)

,file,year,geography,theme,rows,columns,missing_values,duplicate_codes,unique_codes,negative_values,key_join_column,area_name_column,first_few_columns
0,2011_age_LA.csv,2011,LA,age,348,106,0,0,348,0,geography code,geography,date; geography; geography code; Rural Urban; Age: All categories: Age; measures: Value; Age: Age under 1; measures:...
1,2011_sex_LA.csv,2011,LA,sex,348,7,0,0,348,0,geography code,geography,date; geography; geography code; Rural Urban; Sex: All persons; measures: Value; Sex: Males; measures: Value
2,2011_ethnicity_LA.csv,2011,LA,ethnicity,348,28,0,0,348,0,geography code,geography,date; geography; geography code; Rural Urban; Ethnic Group: All categories: Ethnic group; measures: Value; Ethnic Gr...
3,2011_unpaid_care_LA.csv,2011,LA,unpaid care,348,9,0,0,348,0,geography code,geography,date; geography; geography code; Rural Urban; Care Provision: All categories: Provision of unpaid care; measures: Va...
4,2011_economic_activity_LA.csv,2011,LA,economic activity,348,201,0,0,348,0,geography code,geography,date; geography; geography code; Sex: All persons; Age: All categories: Age 16 and over; Economic Activity: All cate...
5,2021_age_LA.csv,2021,LA,age,331,116,0,0,331,0,geography code,geography,date; geography; geography code; Age: Total; measures: Value; Age: Aged 4 years and under; measures: Value; Age: Age...
6,2021_sex_LA.csv,2021,LA,sex,331,6,0,0,331,0,geography code,geography,date; geography; geography code; Sex: All persons; measures: Value; Sex: Female; measures: Value; Sex: Male; measure...
7,2021_ethnicity_LA.csv,2021,LA,ethnicity,331,28,0,0,331,0,geography code,geography,"date; geography; geography code; Ethnic group: Total: All usual residents; Ethnic group: Asian, Asian British or Asi..."
8,2021_unpaid_care_LA.csv,2021,LA,unpaid care,331,12,0,0,331,0,geography code,geography,date; geography; geography code; Provision of unpaid care: Total: All usual residents aged 5 and over; Provision of ...
9,2021_economic_activity_LA.csv,2021,LA,economic activity,331,34,0,0,331,0,geography code,geography,date; geography; geography code; Economic activity status: Total: All usual residents aged 16 years and over; Econom...
10,2021_age_MSOA.csv,2021,MSOA,age,7264,116,0,0,7264,0,geography code,geography,date; geography; geography code; Age: Total; measures: Value; Age: Aged 4 years and under; measures: Value; Age: Age...
11,2021_sex_MSOA.csv,2021,MSOA,sex,7264,6,0,0,7264,0,geography code,geography,date; geography; geography code; Sex: All persons; measures: Value; Sex: Female; measures: Value; Sex: Male; measure...
12,2021_ethnicity_MSOA.csv,2021,MSOA,ethnicity,7264,28,0,0,7264,0,geography code,geography,"date; geography; geography code; Ethnic group: Total: All usual residents; Ethnic group: Asian, Asian British or Asi..."
13,2021_unpaid_care_MSOA.csv,2021,MSOA,unpaid care,7264,12,0,0,7264,0,geography code,geography,date; geography; geography code; Provision of unpaid care: Total: All usual residents aged 5 and over; Provision of ...
14,2021_economic_activity_MSOA.csv,2021,MSOA,economic activity,7264,34,0,0,7264,0,geography code,geography,date; geography; geography code; Economic activity status: Total: All usual residents aged 16 years and over; Econom...

In [9]:
#Add notes to help guide future decision making; core is what the main project scope while stretch depends on time
notes = {
    "2011_age_LA.csv": ["single-year ages; useful for custom age bands", "core"],
    "2011_sex_LA.csv": ["simple male/female table; use as context only", "core"],
    "2011_ethnicity_LA.csv": ["broad groups are comparable; detailed subgroups not needed", "core/stretch"],
    "2011_unpaid_care_LA.csv": ["main outcome; denominator appears to be all usual residents", "core"],
    "2011_economic_activity_LA.csv": ["large table with sex and age breakdowns; use all-persons 16+ columns first", "core"],

    "2021_age_LA.csv": ["has grouped and single-year ages; grouped bands are enough", "core"],
    "2021_sex_LA.csv": ["simple male/female table; use as context only", "core"],
    "2021_ethnicity_LA.csv": ["broad groups align well enough with 2011", "core/stretch"],
    "2021_unpaid_care_LA.csv": ["main outcome; denominator is residents aged 5+", "core"],
    "2021_economic_activity_LA.csv": ["cleaner than 2011; active full-time students need adding back for broad active total", "core"],

    "2021_age_MSOA.csv": ["needed for neighbourhood age structure and projections", "core"],
    "2021_sex_MSOA.csv": ["needed as a light-touch context variable", "core"],
    "2021_ethnicity_MSOA.csv": ["use broad groups and diversity index; avoid detailed subgroup story", "core/stretch"],
    "2021_unpaid_care_MSOA.csv": ["main MSOA outcome for maps, projections and modelling", "core"],
    "2021_economic_activity_MSOA.csv": ["keep inactive subcategories because they help explain care patterns", "core"],
}

audit_table["issue_or_note"] = audit_table["file"].map(lambda x: notes[x][0])
audit_table["decision"] = audit_table["file"].map(lambda x: notes[x][1])

display(audit_table[[
    "file", "year", "geography", "theme", "rows", "columns",
    "missing_values", "duplicate_codes", "negative_values",
    "key_join_column", "issue_or_note", "decision"
]])

,file,year,geography,theme,rows,columns,missing_values,duplicate_codes,negative_values,key_join_column,issue_or_note,decision
0,2011_age_LA.csv,2011,LA,age,348,106,0,0,0,geography code,single-year ages; useful for custom age bands,core
1,2011_sex_LA.csv,2011,LA,sex,348,7,0,0,0,geography code,simple male/female table; use as context only,core
2,2011_ethnicity_LA.csv,2011,LA,ethnicity,348,28,0,0,0,geography code,broad groups are comparable; detailed subgroups not needed,core/stretch
3,2011_unpaid_care_LA.csv,2011,LA,unpaid care,348,9,0,0,0,geography code,main outcome; denominator appears to be all usual residents,core
4,2011_economic_activity_LA.csv,2011,LA,economic activity,348,201,0,0,0,geography code,large table with sex and age breakdowns; use all-persons 16+ columns first,core
5,2021_age_LA.csv,2021,LA,age,331,116,0,0,0,geography code,has grouped and single-year ages; grouped bands are enough,core
6,2021_sex_LA.csv,2021,LA,sex,331,6,0,0,0,geography code,simple male/female table; use as context only,core
7,2021_ethnicity_LA.csv,2021,LA,ethnicity,331,28,0,0,0,geography code,broad groups align well enough with 2011,core/stretch
8,2021_unpaid_care_LA.csv,2021,LA,unpaid care,331,12,0,0,0,geography code,main outcome; denominator is residents aged 5+,core
9,2021_economic_activity_LA.csv,2021,LA,economic activity,331,34,0,0,0,geography code,cleaner than 2011; active full-time students need adding back for broad active total,core
10,2021_age_MSOA.csv,2021,MSOA,age,7264,116,0,0,0,geography code,needed for neighbourhood age structure and projections,core
11,2021_sex_MSOA.csv,2021,MSOA,sex,7264,6,0,0,0,geography code,needed as a light-touch context variable,core
12,2021_ethnicity_MSOA.csv,2021,MSOA,ethnicity,7264,28,0,0,0,geography code,use broad groups and diversity index; avoid detailed subgroup story,core/stretch
13,2021_unpaid_care_MSOA.csv,2021,MSOA,unpaid care,7264,12,0,0,0,geography code,"main MSOA outcome for maps, projections and modelling",core
14,2021_economic_activity_MSOA.csv,2021,MSOA,economic activity,7264,34,0,0,0,geography code,keep inactive subcategories because they help explain care patterns,core

In [10]:
"""
Check geography counts:  2011 and 2021 Local Authority files do not have the same number of areas
"""

la_2011_codes = pd.read_csv(files["2011_age_la"])["geography code"]
la_2021_codes = pd.read_csv(files["2021_age_la"])["geography code"]

matched_codes = set(la_2011_codes).intersection(set(la_2021_codes))
only_2011 = sorted(set(la_2011_codes) - set(la_2021_codes))
only_2021 = sorted(set(la_2021_codes) - set(la_2011_codes))

print("2011 LA codes:", la_2011_codes.nunique())
print("2021 LA codes:", la_2021_codes.nunique())
print("matched codes:", len(matched_codes))
print("2011-only codes:", len(only_2011))
print("2021-only codes:", len(only_2021))

2011 LA codes: 348
2021 LA codes: 331
matched codes: 323
2011-only codes: 25
2021-only codes: 8

In [11]:
"""
The lookup files are needed for two reasons:

1. To convert 2011 Local Authorities onto 2021 boundaries
2.To connect 2021 MSOAs to their Local Authority

"""

msoa_lookup = pd.read_csv(lookup_files["msoa_to_la"], dtype=str, low_memory=False)
la_lookup = pd.read_csv(lookup_files["la_2011_to_2021"], dtype=str)

print("msoa lookup shape:", msoa_lookup.shape)
print("la lookup shape:", la_lookup.shape)

print("\nmsoa lookup columns:")
print(list(msoa_lookup.columns))

print("\nla lookup columns:")
print(list(la_lookup.columns))

msoa lookup shape: (188880, 11)
la lookup shape: (348, 7)

msoa lookup columns:
['OA21CD', 'LSOA21CD', 'LSOA21NM', 'LSOA21NMW', 'MSOA21CD', 'MSOA21NM', 'MSOA21NMW', 'LAD22CD', 'LAD22NM', 'LAD22NMW', 'ObjectId']

la lookup columns:
['LAD11CD', 'LAD11NM', 'LAD11NMW', 'LAD21CD', 'LAD21NM', 'LAD21NMW', 'ObjectId']

In [12]:
msoa_to_la = msoa_lookup[["MSOA21CD", "MSOA21NM", "LAD22CD", "LAD22NM"]].drop_duplicates()
la_2011_to_2021 = la_lookup[["LAD11CD", "LAD11NM", "LAD21CD", "LAD21NM"]].drop_duplicates()

print("unique msoas in lookup:", msoa_to_la["MSOA21CD"].nunique())
print("unique local authorities in msoa lookup:", msoa_to_la["LAD22CD"].nunique())

check = msoa_to_la.groupby("MSOA21CD")["LAD22CD"].nunique()
print("msoas linked to more than one la:", (check > 1).sum())

print("\n2011 authorities in lookup:", la_2011_to_2021["LAD11CD"].nunique())
print("2021 authorities in lookup:", la_2011_to_2021["LAD21CD"].nunique())

unique msoas in lookup: 7264
unique local authorities in msoa lookup: 331
msoas linked to more than one la: 0

2011 authorities in lookup: 348
2021 authorities in lookup: 331

In [13]:
# Unpaid care data
age_total_2011 = "Age: All categories: Age; measures: Value"
care_total_2011 = "Care Provision: All categories: Provision of unpaid care; measures: Value"

age_2011 = pd.read_csv(files["2011_age_la"])[["geography code", age_total_2011]]
care_2011 = pd.read_csv(files["2011_unpaid_care_la"])[["geography code", care_total_2011]]

care_check_2011 = age_2011.merge(care_2011, on="geography code")
care_check_2011["difference"] = care_check_2011[age_total_2011] - care_check_2011[care_total_2011]

print("2011 max absolute difference between age total and care total:")
print(care_check_2011["difference"].abs().max())

2011 max absolute difference between age total and care total:
0

In [14]:
age_total_2021 = "Age: Total; measures: Value"
care_total_2021 = "Provision of unpaid care: Total: All usual residents aged 5 and over"

age_2021 = pd.read_csv(files["2021_age_la"])[["geography code", age_total_2021]]
care_2021 = pd.read_csv(files["2021_unpaid_care_la"])[["geography code", care_total_2021]]

care_check_2021 = age_2021.merge(care_2021, on="geography code")
care_check_2021["age_minus_care_denominator"] = care_check_2021[age_total_2021] - care_check_2021[care_total_2021]

print("2021 max difference between age total and care denominator:")
print(care_check_2021["age_minus_care_denominator"].max())

display(care_check_2021.sort_values("age_minus_care_denominator", ascending=False).head())

2021 max difference between age total and care denominator:
75020

,geography code,Age: Total; measures: Value,Provision of unpaid care: Total: All usual residents aged 5 and over,age_minus_care_denominator
130,E08000025,1144916,1069896,75020
70,E08000035,811950,765153,46797
67,E08000032,546409,510315,36094
38,E08000003,551943,517560,34383
227,E06000060,553081,522190,30891

In [15]:
# checking join works well

msoa_codes = pd.read_csv(files["2021_age_msoa"])[["geography code"]].rename(columns={"geography code": "msoa_code"})

msoa_to_la_clean = msoa_to_la.rename(columns={
    "MSOA21CD": "msoa_code",
    "MSOA21NM": "msoa_name",
    "LAD22CD": "la_code_2021",
    "LAD22NM": "la_name_2021"
})

joined = msoa_codes.merge(msoa_to_la_clean, on="msoa_code", how="left")

print("msoa rows:", len(joined))
print("missing local authority codes after join:", joined["la_code_2021"].isna().sum())
print("unique local authorities after join:", joined["la_code_2021"].nunique())

msoa rows: 7264
missing local authority codes after join: 0
unique local authorities after join: 331

In [16]:
# Final audit summary
summary_points = [
    "All 15 census files opened successfully.",
    "No missing values or duplicate geography codes were found in the census files.",
    "2011 has 348 Local Authorities while 2021 has 331, so 2011 areas must be aggregated to 2021 boundaries before change is calculated.",
    "The 2021 MSOA files need the official MSOA-to-LA lookup because they do not contain Local Authority codes.",
    "The 2011 unpaid-care denominator matches the total population, while the 2021 unpaid-care denominator is residents aged 5 and over.",
    "For the LA change comparison, I will use a harmonised all-age denominator for unpaid care.",
    "For ordinary 2021-only MSOA percentages, I will use each table's own denominator.",
    "The 2021 economic activity file has useful inactive subcategories that should be kept for MSOA analysis.",
]

for point in summary_points:
    print("-", point)

- All 15 census files opened successfully.
- No missing values or duplicate geography codes were found in the census files.
- 2011 has 348 Local Authorities while 2021 has 331, so 2011 areas must be aggregated to 2021 boundaries before change is calculated.
- The 2021 MSOA files need the official MSOA-to-LA lookup because they do not contain Local Authority codes.
- The 2011 unpaid-care denominator matches the total population, while the 2021 unpaid-care denominator is residents aged 5 and over.
- For the LA change comparison, I will use a harmonised all-age denominator for unpaid care.
- For ordinary 2021-only MSOA percentages, I will use each table's own denominator.
- The 2021 economic activity file has useful inactive subcategories that should be kept for MSOA analysis.

In [17]:
# Save audit tabe
audit_table.to_csv(output_path / "data_audit_table.csv", index=False)

lookup_summary = pd.DataFrame([
    {
        "file": "MSOA_to_LA.csv",
        "rows_before_deduplication": len(msoa_lookup),
        "rows_after_deduplication": len(msoa_to_la),
        "unique_msoas": msoa_to_la["MSOA21CD"].nunique(),
        "unique_2021_las": msoa_to_la["LAD22CD"].nunique(),
        "decision": "use to add LA codes to MSOA files",
    },
    {
        "file": "2011_to_2021_LA.csv",
        "rows_before_deduplication": len(la_lookup),
        "rows_after_deduplication": len(la_2011_to_2021),
        "unique_msoas": "not applicable",
        "unique_2021_las": la_2011_to_2021["LAD21CD"].nunique(),
        "decision": "use to aggregate 2011 LAs to 2021 boundaries",
    },
])

lookup_summary.to_csv(output_path / "lookup_audit_table.csv", index=False)

print("saved:", output_path / "data_audit_table.csv")
print("saved:", output_path / "lookup_audit_table.csv")

saved: /Users/eduvieojoboh/Downloads/Visual_analytics/Data/outputs/data_audit_table.csv
saved: /Users/eduvieojoboh/Downloads/Visual_analytics/Data/outputs/lookup_audit_table.csv